# Generated by Django 5.2.12 on 2026-04-06 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_type_preferences', models.CharField(blank=True, choices=[('', '-- Select --'), ('public', 'Public'), ('private', 'Private'), ('ivy_league', 'Ivy League'), ('liberal_arts', 'Liberal Arts'), ('community_college', 'Community College'), ('hbcu', 'HBCU'), ('other', 'Other')], default='', max_length=20)),
                ('meal_plan_preference', models.CharField(choices=[('no_preference', 'No Preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('non_veg', 'Non-Vegetarian'), ('halal', 'Halal'), ('kosher', 'Kosher')], default='no_preference', max_length=15)),
                ('preferred_state', models.CharField(blank=True, default='', help_text='Preferred state (e.g., California)', max_length=100)),
                ('preferred_setting', models.CharField(blank=True, choices=[('', 'Any'), ('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], default='', max_length=15)),
                ('max_distance_from_home', models.PositiveIntegerField(blank=True, default=0, help_text='Miles from home (0 = no limit)')),
                ('preferred_climate', models.CharField(blank=True, choices=[('', 'No preference'), ('warm', 'Warm'), ('cold', 'Cold'), ('temperate', 'Temperate'), ('tropical', 'Tropical')], default='', max_length=15)),
                ('preferred_campus_size', models.CharField(blank=True, choices=[('', 'Any'), ('small', 'Small (<5,000)'), ('medium', 'Medium (5,000-15,000)'), ('large', 'Large (>15,000)')], default='', max_length=10)),
                ('extracurriculars', models.CharField(blank=True, default='', help_text='Hold Ctrl/Cmd to select multiple.', max_length=300)),
                ('preferred_housing', models.CharField(blank=True, choices=[('', 'No preference'), ('dorm', 'Dormitory'), ('apartment', 'Off-campus Apartment'), ('commuter', 'Commuter')], default='', max_length=15)),
                ('sports_program_preference', models.CharField(blank=True, choices=[('', 'No preference'), ('d1', 'Division I'), ('d2', 'Division II'), ('d3', 'Division III'), ('naia', 'NAIA'), ('intramural', 'Intramural Only')], default='', max_length=15)),
                ('gpa_self_assessment', models.CharField(blank=True, default='', help_text='Approximate GPA on a 4.0 scale', max_length=10)),
                ('sat_act_score', models.PositiveIntegerField(blank=True, default=0, help_text='SAT/ACT score (0 = N/A)')),
                ('financial_aid_needed', models.BooleanField(default=False, help_text='Do you need financial aid?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
