# Generated by Django 5.2.12 on 2026-04-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='campus_setting',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='college',
            name='campus_size',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('small', 'Small (<5,000)'), ('medium', 'Medium (5,000–15,000)'), ('large', 'Large (>15,000)')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='college',
            name='climate',
            field=models.CharField(blank=True, choices=[('', 'No preference'), ('warm', 'Warm'), ('cold', 'Cold'), ('temperate', 'Temperate'), ('tropical', 'Tropical')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='college',
            name='extracurriculars',
            field=models.CharField(blank=True, default='', help_text='Comma-separated highlights (sports, music, Greek life, …).', max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='financial_aid_available',
            field=models.BooleanField(default=True, help_text='Uncheck if the profile should not match financial-aid-related searches.'),
        ),
        migrations.AddField(
            model_name='college',
            name='housing_summary',
            field=models.CharField(blank=True, default='', help_text='Housing options (dorms, apartments, commuter-friendly, …).', max_length=200),
        ),
        migrations.AddField(
            model_name='college',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('public', 'Public'), ('private', 'Private'), ('ivy_league', 'Ivy League'), ('liberal_arts', 'Liberal Arts'), ('community_college', 'Community College'), ('hbcu', 'HBCU'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='meal_options',
            field=models.CharField(blank=True, default='', help_text='Dining/diet options offered (e.g. vegetarian, halal, kosher).', max_length=300),
        ),
        migrations.AddField(
            model_name='college',
            name='search_notes',
            field=models.TextField(blank=True, default='', help_text='Extra searchable text: nicknames, programs, anything students might type.'),
        ),
        migrations.AddField(
            model_name='college',
            name='sports_program',
            field=models.CharField(blank=True, choices=[('', 'No preference'), ('d1', 'Division I'), ('d2', 'Division II'), ('d3', 'Division III'), ('naia', 'NAIA'), ('intramural', 'Intramural only')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State or region (searchable alongside location).', max_length=100),
        ),
    ]
